/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var WhereAmI:String = "event:/Music/WhereAmI";
}

class FmodSFX {
    public static inline var ScrapPickup:String = "event:/SFX/Collectables/ScrapPickup";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var PlayerDodge:String = "event:/SFX/Player/PlayerDodge";
    public static inline var PlayerStep:String = "event:/SFX/Player/PlayerStep";
}
