/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var ForScrap:String = "event:/Music/ForScrap";
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var WhereAmI:String = "event:/Music/WhereAmI";
}

class FmodSFX {
    public static inline var ScrapPickup:String = "event:/SFX/Collectables/ScrapPickup";
    public static inline var ScrapSpawnDeposited:String = "event:/SFX/Collectables/ScrapSpawnDeposited";
    public static inline var ScrapSpawnDeposited2:String = "event:/SFX/Collectables/ScrapSpawnDeposited2";
    public static inline var ScrapSpawnDepositedComplete:String = "event:/SFX/Collectables/ScrapSpawnDepositedComplete";
    public static inline var CollectorGrinding:String = "event:/SFX/Collector/CollectorGrinding";
    public static inline var CollectorOpen:String = "event:/SFX/Collector/CollectorOpen";
    public static inline var DoorOpen:String = "event:/SFX/Door/DoorOpen";
    public static inline var DoorOpen2:String = "event:/SFX/Door/DoorOpen2";
    public static inline var GunGet:String = "event:/SFX/Guns/GunGet";
    public static inline var GunGetJingle:String = "event:/SFX/Guns/GunGetJingle";
    public static inline var GunSpawn:String = "event:/SFX/Guns/GunSpawn";
    public static inline var GunsPistol:String = "event:/SFX/Guns/GunsPistol";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var PlayerDodge:String = "event:/SFX/Player/PlayerDodge";
    public static inline var PlayerGetHit:String = "event:/SFX/Player/PlayerGetHit";
    public static inline var PlayerStep:String = "event:/SFX/Player/PlayerStep";
    public static inline var TargetHit:String = "event:/SFX/Target/TargetHit";
    public static inline var TargetHit2:String = "event:/SFX/Target/TargetHit2";
    public static inline var TargetHit3:String = "event:/SFX/Target/TargetHit3";
    public static inline var TargetHit4:String = "event:/SFX/Target/TargetHit4";
    public static inline var TinkShutter:String = "event:/SFX/Tink/TinkShutter";
    public static inline var TinkTalk:String = "event:/SFX/Tink/TinkTalk";
    public static inline var TrashHit:String = "event:/SFX/Trash/TrashHit";
}
